// Code generated by "stringer -type OnErrorAction ./cmd/kong"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[allow-0]
	_ = x[null-1]
	_ = x[skip-2]
	_ = x[abort-3]
}

const _OnErrorAction_name = "allownullskipabort"

var _OnErrorAction_index = [...]uint8{0, 5, 9, 13, 18}

func (i OnErrorAction) String() string {
	if i < 0 || i >= OnErrorAction(len(_OnErrorAction_index)-1) {
		return "OnErrorAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OnErrorAction_name[_OnErrorAction_index[i]:_OnErrorAction_index[i+1]]
}
